{{- if .Values.ingressRouteTCP.enabled -}}
{{- $fullName := include "bss.fullname" . -}}
{{- $svcPort := "" -}}
{{- $svcName := $fullName -}}
{{- if kindIs "slice" .Values.service -}}
  {{- $firstService := index .Values.service 0 -}}
  {{- $svcName = printf "%s-%s" $fullName ($firstService.name | default "service") -}}
  {{- if kindIs "slice" $firstService.port -}}
    {{- $svcPort = index $firstService.port 0 -}}
  {{- else -}}
    {{- $svcPort = $firstService.port -}}
  {{- end -}}
{{- else -}}
  {{- if kindIs "slice" .Values.service.port -}}
    {{- $svcPort = index .Values.service.port 0 -}}
  {{- else -}}
    {{- $svcPort = .Values.service.port -}}
  {{- end -}}
{{- end -}}
---
{{- if .Values.ingressRouteTCP.tls.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $fullName }}-tcp-tls
  labels:
    {{- include "bss.labels" . | nindent 4 }}
spec:
  commonName: {{ .Values.ingressRouteTCP.host }}
  dnsNames:
    - {{ .Values.ingressRouteTCP.host }}
  issuerRef:
    kind: {{ .Values.ingressRouteTCP.tls.certIssuerKind | default "ClusterIssuer" }}
    name: {{ .Values.ingressRouteTCP.tls.certIssuer }}
  secretName: {{ $fullName }}-tcp-tls
---
{{- end }}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ $fullName }}-tcp
  labels:
    {{- include "bss.labels" . | nindent 4 }}
  {{- with .Values.ingressRouteTCP.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  entryPoints:
    {{- range .Values.ingressRouteTCP.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
  - match: HostSNI(`{{ .Values.ingressRouteTCP.host }}`)
    services:
    - name: {{ $svcName }}
      port: {{ $svcPort }}
  {{- if .Values.ingressRouteTCP.tls.enabled }}
  tls:
    secretName: {{ $fullName }}-tcp-tls
    {{- if .Values.ingressRouteTCP.tls.passthrough }}
    passthrough: true
    {{- end }}
  {{- end }}
{{- end }}
