{{- if kindIs "slice" .Values.service }}
{{- range $index, $service := .Values.service }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bss.fullname" $ }}{{ if $service.name }}-{{ $service.name }}{{ else if gt (len $.Values.service) 1 }}-{{ $index }}{{ end }}
  {{- with $service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "bss.labels" $ | nindent 4 }}
    {{- with $service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ $service.type | default "ClusterIP" }}
  {{- if $service.ports }}
  ports:
    {{- range $service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name | default "http" }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  {{- else }}
  ports:
    - port: {{ $service.port | default 80 }}
      targetPort: {{ $service.targetPort | default "http" }}
      protocol: TCP
      name: http
  {{- end }}
  {{- if $service.selector }}
  selector:
    {{- toYaml $service.selector | nindent 4 }}
  {{- else }}
  selector:
    {{- include "bss.selectorLabels" $ | nindent 4 }}
  {{- end }}
{{- end }}
{{- else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bss.fullname" . }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "bss.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  {{- if .Values.service.ports }}
  ports:
    {{- range .Values.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort | default .port }}
      protocol: {{ .protocol | default "TCP" }}
      name: {{ .name | default "http" }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
    {{- end }}
  {{- else }}
  ports:
    - port: {{ .Values.service.port | default 80 }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  {{- end }}
  {{- if .Values.service.selector }}
  selector:
    {{- toYaml .Values.service.selector | nindent 4 }}
  {{- else }}
  selector:
    {{- include "bss.selectorLabels" . | nindent 4 }}
  {{- end }}
{{- end }}
